### ISSUE TITLE
Add target uninstall

### ISSUE THREAD

**Issue by RaghavRao** [nelhage/reptyr#105]
Here's what I added to my Makefile to add the uninstall target:
```
@@ -57,4 +58,14 @@ install: reptyr
        install -d -m 755 $(DESTDIR)$$bashcompdir ; \
        install -m 644 reptyr.bash $(DESTDIR)$$bashcompdir/reptyr
 
+BASHCOMPDIR ?= $(shell $(PKG_CONFIG) --variable=completionsdir bash-completion 2>/dev/null)
+
+uninstall: reptyr
+       rm $(DESTDIR)$(BINDIR)/reptyr
+       rm $(DESTDIR)$(MANDIR)/man1/reptyr.1
+       rm $(DESTDIR)$(MANDIR)/fr/man1/reptyr.1
+       bashcompdir=$(BASHCOMPDIR) ; \
+       test -z "$$bashcompdir" && bashcompdir=/etc/bash_completion.d ; \
+       rm $(DESTDIR)$$bashcompdir/reptyr
+

```

I didn't know if it was worth a PR. Is it?

**Comment by nelhage** [comment]
I'm a bit skeptical of `uninstall` targets since I feel like the use case is almost always better met by some out-of-band tool like GNU stow which is capable of properly sandboxing installations and doesn't require manually keeping the lists in sync, but I'd accept the PR if it's helpful to you for some reason.

**Comment by RaghavRao** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Stow seems a lot nicer. I added the uninstall after several failed attempts with checkinstall on Fedora 31 but stow seems perfect. I suppose an uninstall target would be redundant. Could a mention of stow be made in the Readme or wiki? Thanks!                                                                                                                                                                           From: notifications@github.comSent: November 18, 2019 13:12To: reptyr@noreply.github.comReply-to: reply@reply.github.comCc: raghav.rao32@gmail.com; author@noreply.github.comSubject: Re: [nelhage/reptyr] Add target uninstall (#105)  I'm a bit skeptical of uninstall targets since I feel like the use case is almost always better met by some out-of-band tool like GNU stow which is capable of properly sandboxing installations and doesn't require manually keeping the lists in sync, but I'd accept the PR if it's helpful to you for some reason.
