### ISSUE TITLE
Possible addition of version for later (>= 18) Ubuntu aarch64 distributions?

### ISSUE THREAD

**Issue by PaPaTheGMan** [nelhage/reptyr#121]
Just ran across this utility, absolutely fantastic.  Thank you very much.  I have Ubuntu aarch64 servers running various (16 LTS, 18 LTS & 20 LTS) distributions.  Your utility is in the distribution package for 16, but not the others.  Would like to put a vote in for it to be added.  Thanks again.

P.S., I note it is in the 18.. x86_64 distribution.

**Comment by nelhage** [comment]
Thanks for the kind words! I don't control the Ubuntu packaging; if you want to request that they package it for new versions or architectures, I believe you'll need to open a bug in the Ubuntu bug trackers.
