### ISSUE TITLE
Reptyr works for binaries but not for scripts

### ISSUE THREAD

**Issue by bidaian** [nelhage/reptyr#13]
I'm using nelhage-reptyr-61cc5f8 on Ubuntu 10.04.3 LTS).  On a terminal I created a script like this:

#!/bin/bash

while true
do
	sleep 5
	date
done

Once I started it I open another terminal and tried to reptyr the bash process, or the parent bash process.  The original one was stopped (as if ^Z had been typed) but the output was still coming out on the original terminal.  Maybe that's normal behaviour for scripts but just in case I report it.

**Comment by nelhage** [comment]
The new `-T` option should work properly for scripts under most circumstances!

**Comment by jpbruyere** [comment]
+1 for -T option
