### ISSUE TITLE
more a question about installing? 

### ISSUE THREAD

**Issue by RyanZurrin** [nelhage/reptyr#144]
Is it possible to install reptyr on a remote server where I work without having sudo access? Everything I find about installing, even from source, requires the use of sudo, and it would be good to have a way to install without sudo if possible. Thanks for any help.

**Comment by PythonNut** [comment]
You can always just add `reptyr` to your `PATH` after building. For example, I have `~/.local/bin` in my `PATH` (which I set in my `.bashrc`) and I symlinked `reptyr` into `~/.local/bin` so I can use it anywhere.

**Comment by RyanZurrin** [comment]
Perfect and simple solution, thanks!
