### ISSUE TITLE
Doesn't work for processes which have spawned subprocesses

### ISSUE THREAD

**Issue by therealprologic** [nelhage/reptyr#24]
See:

```
# reptyr $(pgrep pkgmk)
[-] Process 4646 (pkgmk) shares 4604's process group. Unable to attach.
(This most commonly means that 4604 has a suprocesses).
Unable to attach to pid 4604: Invalid argument
```

**Comment by melikyuksel** [comment]
Why was this closed even though it still doesn't work?

**Comment by nelhage** [comment]
@melikyuksel It should work with `-T` in most cases, and I don't know of a way to make it work in reptyr's default mode, due to fundamental limitations of the terminal APIs exposed by the kernel. If you have specific issues with `-T`, feel free to open a new issue.

**Comment by mystica555** [comment]
reptyr -T worked fine for me with a stuck old dpkg process that spawned a whiptail subshell for configuration options from another ssh session. 

Great work!

**Comment by infinity0** [comment]
You can `reptyr -T` the same process twice, the second time you just have to give the PID of the `reptyr` process that you used the first time.

Your terminal ends up in a weird state where you can type in commands but the process is running "at the same time" in the background, but since it is not a direct child of the shell, you can't do `fg` or `bg` to get it back under your control.

Still, it's useful if you need to move a long-running build process around into a different terminal just to keep it alive, for whatever reason.

**Comment by akashaggarwal7** [comment]
@infinity0 Thanks! That worked wonders. Quick question, if I have to do it for the third time, I'd still be using the PID of first reptyr right?

**Comment by infinity0** [comment]
@akashaggarwal7 not sure, but you can run `pstree -alpu` to see which processes still exist and how they're all related.

**Comment by JeromeJ** [comment]
Completely ignore the `-T` argument for me, it isn't even listed in `--help`. I got version 0.5, when has this been implemented? I've got the latest version offered by my source depot on Debian 8.

**Comment by Sandoras** [comment]
@JeromeJ I have the exact same problem. I found out I have the 0.5 version also, which is about 4 years old now. Since I am new to Linux all in all, I need to figure out how i can upgrade something that is already in the source depot.. Oh well, at least I'm having fun.

**Comment by Smattr** [comment]
@Sandoras you're new to Linux but you're running reptyr... You really have chosen to dive in at the deep end :)

Some minimal steps to get a runnable version of the github tip if you don't care about Bash completion and do not have root/sudo:

    $ git clone https://github.com/nelhage/reptyr
    $ cd reptyr
    $ mkdir -p /path/where/reptyr/will/live
    $ make PREFIX=/path/where/reptyr/will/live BASHCOMPDIR=$(mktemp -d) install
    $ /path/where/reptyr/will/live/bin/reptyr --help

HTH

**Comment by Sandoras** [comment]
@Smattr Thank you! I already installed the 5.0 version of reptyr via apt-get. This will still work? And what directory do you suppose I can put it in?

**Comment by Smattr** [comment]
Did you mean version 0.5? [It doesn't look to me like it's reached 5.0](https://github.com/nelhage/reptyr/blob/master/reptyr.h#L23).

As far as I'm aware, the two versions should happily co-exist if that's what you're asking. You might want to uninstall the apt-get-provided version to avoid confusion though.

With regards to what directory to put it in, Linux isn't particularly picky about where you put things. For example, you could install it to ~/reptyr and then run it as `~/reptyr/bin/reptyr`. If you want to be able to run it by just typing `reptyr` you'll want to look into modifying your `PATH` variable and your ~/.bashrc or equivalent. Some searching online should turn up plenty of advice for doing this.

**Comment by RSully** [comment]
@BarbzYHOOL did you ever find a solution to this? I have a process that I failed to capture and is now a child of systemd that gives that error

**Comment by Smattr** [comment]
I don't know how far into debugging this you are but if it helps, the symptoms indicate [your process is not connected to a Unix 98 PTY](https://github.com/nelhage/reptyr/blob/master/platform/linux/linux.c#L269-L270).

[Aside @nelhage, is it deliberate that [`parse_proc_state` uses `%u` for the device number](https://github.com/nelhage/reptyr/blob/master/platform/linux/linux.c#L38-L41) while the [manpage documents it as `%d`](http://man7.org/linux/man-pages/man5/proc.5.html)? I can't see how this would make a difference to the case mentioned above but it seemed surprising.]

**Comment by nelhage** [comment]
@Smattr I don't think there was any reason for that, but I also agree I can't imagine it causing problems in practice.

**Comment by nelhage** [comment]
(I'd happily take a PR to fix if you're feeling motivated)

To the original question, `-T` can't really work, at least I'm not quite sure what it would mean for it to work, if the process isn't attached to a TTY.

**Comment by RSully** [comment]
Yeah I understand `-T` would be undefined in this state, I suppose the question is there *anything* reptyr can do when a process is in this state, thinking outside the box perhaps?

**Comment by cormacncheese** [comment]
Still getting the following error when using `-T`

```
Child is not connected to a pseudo-TTY. Unable to steal TTY.
Unable to attach to pid <PID>: Invalid argument
```

Any workaround for this? I'm logged in as root

**Comment by KaKi87** [comment]
> it won't normally work on sessions that are spawned out of an `ssh` session unless the attaching `reptyr` is run as root

What if the initial command was run as another user than `root` ?

I'm currently in that case, and running `reptyr -T <pid>` as `root` throws *permission denied*, which I suppose is because of that.

Thanks
