### ISSUE TITLE
Error on chown() function in attach.c

### ISSUE THREAD

**Issue by gtmanfred** [nelhage/reptyr#50]
I am getting this error when trying to package it on arch, and I have no idea how to fix it.

cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -Werror -D_GNU_SOURCE -g -D_FORTIFY_SOURCE=2  -c -o reptyr.o reptyr.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -Werror -D_GNU_SOURCE -g -D_FORTIFY_SOURCE=2  -c -o reallocarray.o reallocarray.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -Werror -D_GNU_SOURCE -g -D_FORTIFY_SOURCE=2  -c -o attach.o attach.c
attach.c: In function ‘setup_steal_socket’:
attach.c:387:5: error: ignoring return value of ‘chown’, declared with attribute warn_unused_result [-Werror=unused-result]
     chown(steal->addr_un.sun_path, steal->target_stat.uid, steal->target_stat.gid);
     ^
attach.c:388:5: error: ignoring return value of ‘chown’, declared with attribute warn_unused_result [-Werror=unused-result]
     chown(steal->tmpdir, steal->target_stat.uid, steal->target_stat.gid);
     ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'attach.o' failed
make: *** [attach.o] Error 1

**Comment by nelhage** [comment]
Bah, I should have seen this coming. I'm deliberately ignoring the return value of `chown`, but I should have made that explicit. I'll push a fix. You can likely get to built via `CFLAGS=-Wno-unused-result` or take the next commit. I can push an `0.6.1` tag if that makes your life easier.

**Comment by nelhage** [comment]
closed by d734f5f1b3e4c6be2753be1e1f52a2a4ab7ea4ab and 3960d133c8530c16d1c3bcebcc330b7055778647

**Comment by gtmanfred** [comment]
Sorry, I got busy and couldn't follow up with this.

Thanks!  There was no need to make a release, I could have done the CFLAGs. But since there is a new release anyway, thanks again!

Daniel
