### ISSUE TITLE
Build failure with gcc 7.0.1

### ISSUE THREAD

**Issue by scop** [nelhage/reptyr#81]
Build fails with current Fedora rawhide, gcc 7.0.1:

```
attach.c: In function ‘setup_steal_socket’:
attach.c:393:15: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 108 [-Werror=format-truncation=]
              "%s/reptyr.sock", steal->tmpdir);
               ^~
attach.c:392:5: note: ‘snprintf’ output between 13 and 4108 bytes into a destination of size 108
     snprintf(steal->addr_un.sun_path, sizeof(steal->addr_un.sun_path),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              "%s/reptyr.sock", steal->tmpdir);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by nelhage** [comment]
Hi,

Can you confirm if the `gcc7` branch builds for you? It builds using my `gcc-7` from `ubuntu-toolchain-r/test`, but it'd be good to get confirmation.

Thanks for the report!

**Comment by scop** [comment]
Yep, the gcc7 branch builds for me.

**Comment by nelhage** [comment]
Thanks for the report! I'd love to get this in CI to make sure we don't regress, but I don't see an easy way to get gcc-7 packages in travis right now.

**Comment by scop** [comment]
One way to get gcc7 and pretty much anything would be to use docker in Travis, for inspiration see e.g. what I've done in https://github.com/rpm-software-management/rpmlint (not necessarily the prettiest, but has worked for me).

**Comment by rekm** [comment]
Hi, i just tried packaging tag 0.6.2 into a conda package and ran into the same issue, referenced in OPs first post.
Isn't this [line](https://github.com/nelhage/reptyr/blob/ec891f6993f235014d91328714975e1534b4d2ab/attach.c#L392) always false, because of sprints innate truncation.
   
    if (snprintf(steal->addr_un.sun_path, sizeof(steal->addr_un.sun_path),
                    "%s/reptyr.sock", steal->tmpdir) >= sizeof(steal->addr_un.sun_path)) 
    {
        error("tmpdir path too long!");
        return ENAMETOOLONG;
    }

I hard coded a patch for ubuntu/debian  systems by truncating explicitly,
where addr_un.sun_path = 108. 

    snprintf(steal->addr_un.sun_path, sizeof(steal->addr_un.sun_path),
                 "%.%s/reptyr.sock", steal->tmpdir, sizeof(steal->addr_un.sun_path)-(12+1)) 
                  && strlen(steal->addr_un.sun_path)+1 >= sizeof(steal->addr_un.sun_path)

This version of snprintf obviously lacking type safety because sizeof() returns size_t.
My two cents, that might be based on my erroneous understanding of the snprintf function.

**Comment by nelhage** [comment]
`snprintf` is documented in my man pages as

```
       The functions snprintf() and vsnprintf() do not write  more  than  size
       bytes  (including the terminating null byte ('\0')).  If the output was
       truncated due to this limit, then the return value  is  the  number  of
       characters  (excluding the terminating null byte) which would have been
       written to the final string if enough space had been available.   Thus,
       a  return  value  of  size or more means that the output was truncated.
       (See also below under NOTES.)
```

Which suggests to me that this comparison is a valid way to check for truncation.

I'm not really sure what the right fix is here. `sun_path` is fixed size and I can't change that, and as far as I can tell I'm correctly using `snprintf` to avoid overflow, and detect the truncation and error out, which is pretty much the only correct thing I can do if the path is too long.
