### ISSUE TITLE
PowerPC support?

### ISSUE THREAD

**Issue by grepwood** [nelhage/reptyr#89]
I tried to compile. Didn't work. I tried to read the source, like amd64.h. Where do these magic numbers come from?

**Comment by nelhage** [comment]
The constants describe the x86 syscall convention, as well as some details of how `ptrace` works on that architecture. I'm not familiar with PPC but it *shouldn't* be too hard to add Linux support, unless there's something complex I'm unaware of. Is there an easy way to me to get a test environment, if I were to have time for looking into it?

**Comment by blakehilliard** [comment]
> it shouldn't be too hard

I'd like to be able to use this on PowerPC as well. Any pointers that could turn this from "I have no idea how to make this work" to "it shouldn't be too hard" for me? If I get it working I'll submit a pull request, though I'm not very confident I'll have the time to work on this if it doesn't turn out to be simple.

**Comment by nelhage** [comment]
Indeed,thanks.
