### ISSUE TITLE
X11 stealing?

### ISSUE THREAD

**Issue by SoniEx2** [nelhage/reptyr#93]
unix sockets are unix sockets, so it should be possible to steal an X11 program from normal X11 and into X11-over-ssh, right?

it would be a really useful feature.

**Comment by nelhage** [comment]
Stealing the socket is probably possible, but the X protocol is stateful, and I think you'd need to also figure out how to enumerate and clone any pixmaps or other objects stored on the server. Also, local X11 may have already negotiated extensions like shared memory that aren't available over ssh forwarding. I don't think this is likely to be something I'm going to have time to explore, unfortunately.
