### ISSUE TITLE
Temporary child is left as zombie process

### ISSUE THREAD

**Issue by rohoog** [nelhage/reptyr#95]
The child of the process to reptyr that was used in the setsid trickery stays as a zombie while the reptyr'ed process is running.
This is more like an 'uglyness' than a real problem. It could probably be solved by wait()ing to collect the child's status.

**Comment by nelhage** [comment]
Hm, interesting. The code [does attempt to wait()](https://github.com/nelhage/reptyr/blob/3f46356e6ce6531c138604a20f20cb687f3717e8/attach.c#L114) on the child, so something must be going wrong there. I'm investigating.
